language: php

php:
  - 5.5

services: mysql


before_script:
  # Move all of our files to a subdirectory
  - my_files=`ls -A`
  - mkdir facetedsearch
  - for my_file in $my_files; do mv $my_file facetedsearch/; done
  # we need this at the root though
  - mv facetedsearch/travis-scripts .

  # Install PrestaShop
  - bash travis-scripts/install-prestashop
  # Put module in place
  - mv facetedsearch PrestaShop/modules/

script:
  - cd PrestaShop/modules/facetedsearch
  - composer install --no-dev
  - phpunit
